(require 'srfi-1)

(define (flatmap proc seq)
    (fold-right append '() (map proc seq))
)

(define (enumerate-interval low high)
    (if (> low high)
        '()
        (cons low (enumerate-interval (+ low 1) high))
    )
)

(define (unique-triples n)
    (flatmap
        (lambda (i)
            (flatmap (lambda (j)
                        (map (lambda (k) (list i j k))
                             (enumerate-interval 1 (- j 1))
                        )
                     )
                     (enumerate-interval 1 (- i 1))
            )
        )
        (enumerate-interval 1 n)
    )
)

(define (defined-triples n s)
    (filter (lambda (triple)
                (if (= (+ (car triple) (cadr triple) (caddr triple)) s) #t #f)
            )
            (unique-triples n)
    )
)
